baseURL = "https://sharp-sammet-7aa19b.netlify.app"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
[params]
[[menu.main]]
name = "Introduction"
weight = 1
url = "/introduction/"

[[menu.main]]
name = "Dummy Walkthrough"
weight = 1
url = "/dummywalkthrough/"

[[menu.main]]
name = "Dummy definition"
weight = 1
url = "/dummyresource/"

[[menu.main]]
name = "Dummy Definitions"
weight = 1
url = "/dummydefinitions/"
